// (C) 2010-2021 by ModuleWorks GmbH
// Owner: CutSim

#pragma once
#include "mwDefines.hpp"
//#############################################################################
//--------------------------Included header files ---------------------------//
//#############################################################################
//misc

// Please note this file is published to customers, so internal preprocessor directives
// should be avoided to avoid build errors on the customers side.


#ifndef MW_USE_VS2008_COMPATIBILITY // Minimal subset for mwVerifier
#include "mwActionKeyBinding.hpp"
#include "winCpuTickTimer.hpp"
#include "mwClampedValue.hpp"
#include "mwCollectionOfContainers.hpp"
#include "mwRangeException.hpp"
#include "mwFileName.hpp"
#include "mwFileSystem.hpp"
#include "mwCodecvt.hpp"
#include "mwFileStream.hpp"
#include "mwStream.hpp"
#include "mwBILostData.hpp"
#include "mwException.hpp"
#include "mwmiscException.hpp"
#include "mwParserException.hpp"
#include "mwIdxRangeException.hpp"
#include "mwMathException.hpp"
#include "mwNameValue.h"
#include "mwParamStorage.hpp"
#include "mwParamStorageException.hpp"
#include "mwWinRegParamStorage.hpp"
#include "mwWinRegTextStorage.hpp"
#include "mwWinUnhandledExceptionInformation.hpp"
#include "mwWinRegTextPatchUtils.hpp"
#include "mwResource.hpp"
#include "mwResourceDll.hpp"
#include "mwNeutralResourceDll.hpp"
#include "mwStringOps.hpp"
#include "mwStdInputStream.hpp"
#include "mwStdOutputStream.hpp"
#include "mwCommandLineInfo.hpp"
#include "mwAvoid_Warnings.hpp"
#include "mwAutoPointer.hpp"
#include "mwString.hpp"
#include "mwStringConversions.hpp"
#include "mwStringTokenizer.hpp"
#include "mwBinInputStream.hpp"
#include "mwBinOutputStream.hpp"
#include "mwFileFinder.hpp"
#include "mwEfficientVector.hpp"
#include "mwRealArray2D.hpp"
#include "mwRealArray.hpp"
#include "mwMsgMap.hpp"
#include "mwStopClock.hpp"
#include "mwCriticalSection.hpp"
#include "mwMemoryHeap.hpp"
#include "mwMemoryIOStream.hpp"
#include "mwMemoryMultiAllocator.hpp"
#include "mwMemoryPool.hpp"
#include "mwMemoryPoolArena.hpp"
#include "mwMemoryPoolList.hpp"
#include "mwMemoryVirtual.hpp"
#include "mwBinIOStream.hpp"
#include "mwPresetIOStream.hpp"
#include "mwMemoryException.hpp"
#include "mwWinFileParamStorage.hpp"
#include "mwFileIOStream.hpp"
#include "mwThreadUnsafe.hpp"
#include "mwRealArrayLarge.hpp"
#include "mwChecksum.hpp"
#include "mwDataIntegrityUtils.hpp"
#include "mwXMLUtils.hpp"
#include "mwTiXMLReadWriteHelper.hpp"
#include "mwIniFileService.hpp"
#include "mwCompatibilityChecker.hpp"
#include "mwVersionInfoHelper.hpp"
#include "mwLogger.hpp"
#include "mwTxtOutputStream.hpp"
#include "mwOptional.hpp"
//#############################################################################
//mathdef
#include "mwMathConstants.hpp"
#include "mwTVector.hpp"
#include "mwTVector2.hpp"
#include "mwTVector3.hpp"
#include "mwTrig.hpp"
//#############################################################################
#ifndef _NO_GUI
	//mmedia
	#include "mwColor.hpp"
	#include "mwColorGradient.hpp"
	#include "mwLight.hpp"
	#include "mwTexture.hpp"
	#include "mwMaterial.hpp"
	#include "mwAppearance.hpp"
	#include "mwAppearanceApplier.hpp"
	#include "mwGLReflectionTexture.hpp"
	#include "mwGLRenderingContextPreservingProgressHandlerDecorator.hpp"
#endif
//#############################################################################
//geodef
#include "mwTSphereBase.hpp"
#include "mwTGeometry.hpp"
#include "mwTBaseGeometry.hpp"
#include "mwTBaseGeometry2d.hpp"
#include "mwTGeometry2d.hpp"
#include "mwTBaseGeometry3d.hpp"
#include "mwTGeometry3d.hpp"
#include "mwTGeoFactory.hpp"
#include "mwTCSTranslator.hpp"
#include "mwTView.hpp"
#include "mwTSpaceLocation.hpp"
#include "mwTCoordSystem.hpp"
#include "mwTAbstractCoordSystem2d.hpp"
#include "mwTCoordSystem2d.hpp"
#include "mwTiCoordSystem2d.hpp"
#include "mwTijCoordSystem2d.hpp"
#include "mwTAbstractCoordSystem3d.hpp"
#include "mwTCoordSystem3d.hpp"
#include "mwTiCoordSystem3d.hpp"
#include "mwTijCoordSystem3d.hpp"
#include "mwTijkCoordSystem3d.hpp"
#include "mwTSegmentBase.hpp"
#include "mwTSegment.hpp"
#include "mwTSegmentFactory.hpp"
#include "mwTCircleBase.hpp"
#include "mwTCircle.hpp"
#include "mwTCircleFactory.hpp"
#include "mwTArcCircleBase.hpp"
#include "mwTArcCircle.hpp"
#include "mwTArcCircleFactory.hpp"
#include "mwTEllipseBase.hpp"
#include "mwTEllipse.hpp"
#include "mwTEllipseFactory.hpp"
#include "mwTArcEllipseBase.hpp"
#include "mwTArcEllipse.hpp"
#include "mwTArcEllipseFactory.hpp"
#include "mwTHelix.hpp"
//#############################################################################
//cadcam
#include "mwToolPartDefinition.hpp"
#include "mwCuttingPartDefinition.hpp"
#include "mwNonCuttingPartDefinition.hpp"
#include "mwRevolvedSolidDefinition.hpp"
#include "mwExtrudedSolidDefinition.hpp"
#include "mwMeshSolidDefinition.hpp"
#include "mwTypedExtrudedSolidDefinition.hpp"
#include "mwTurningSolidDefinition.hpp"
#include "mwContourTurningSolidDefinition.hpp"
#include "mwSolidDefinition.hpp"
#include "mwSolidDefinitionCloner.hpp"
#include "mwProfileToShapeIf.hpp"
#include "mwProfileToCylinderApproximation.hpp"
#include "mwRevolveProfileSrv.hpp"
#include "mw2dPoint.hpp"
#include "mw2dContour.hpp"
#include "mw2dClosedContour.hpp"
#include "mw2dLine.hpp"
#include "mw2dGeometry.hpp"
#include "mw2dPolyLine.hpp"
#include "mw2dPolylineUtils.hpp"
#include "mw2dTransformationFactory.hpp"
#include "mwMinSquaredDistance.hpp"
#include "mwGeometryCopy.hpp"
#include "mwCircleUtils.hpp"
#include "mw2dBoundingBox.hpp"
#include "mwHolderDefinition.hpp"
#include "mwArborDefinition.hpp"
#include "mwToolHelper.hpp"
#include "mwTurningToolHelper.hpp"
#include "mwUnitsFactory.hpp"
#include "mwMeasurable.hpp"
#include "mwMeasurablePoint3d.hpp"
#include "mwMeasurableAxis.hpp"
#include "mw2dControlMatrix.hpp"
#include "mw2dPoint3dMatrix.hpp"
#include "mw2dWeightMatrix.hpp"
#include "mwControlPoint.hpp"
#include "mwEndMill.hpp"
#include "mwTPoint3d.hpp"
#include "mw3dObject.hpp"
#include "mw3dGeometry.hpp"
#include "mw3dBoundingBox.hpp"
#include "mw3dPolyLine.hpp"
#include "mw3dPolyLineCutter.hpp"
#include "mw3dLineCutter.hpp"
#include "mw3dPolyLineComparer.hpp"
#include "mw3dLine.hpp"
#include "mw3dPoint.hpp"
#include "mw3dContour.hpp"
#include "mw3dTransformationFactory.hpp"
#include "mw3dPolygonizer.hpp"
#include "mwIntpBezierCurve.hpp"
#include "mw3dArc.hpp"
#include "mwSTLTranslator.hpp"
#include "mwMatrix.hpp"
#include "mwVector.hpp"
#include "mwTPoint2d.hpp"
#include "mwTPoint3d.hpp"
#include "mwTool.hpp"
#include "mwExtrudedTool.hpp"
#include "mwGenericExtrudedTool.hpp"
#include "mwWireTool.hpp"
#include "mwRevolvedTool.hpp"
#include "mwGenericRevolvedTool.hpp"
#include "mwGeneric2TypedToolConverter.hpp"
#include "mwTypedRevolvedTool.hpp"
#include "mwToolCloner.hpp"
#include "mwToolPathTraversers.hpp"
#include "mwUVKnotVectors.hpp"
#include "mw3axMove.hpp"
#include "mw5axMove.hpp"
#include "mwCNCMove.hpp"
#include "mwBullMill.hpp"
#include "mwSphereMill.hpp"
#include "mwLolMill.hpp"
#include "mwTaperMill.hpp"
#include "mwSlotMill.hpp"
#include "mwUVControlPoint.hpp"
#include "mwPointuv.hpp"
#include "mwEnrichedPostedTP.hpp"
#include "mwEnrichedPostedMove.hpp"
#include "mwChuckJawsStateChangeAttribute.hpp"
#include "mwKeepPartsAttribute.hpp"
#include "mwThreadAttribute.hpp"
#include "mwShortestPathRotationAttribute.hpp"
#include "mwRotationAttributeCheck.hpp"
#include "mwEnrichedTool.hpp"
#include "mwBoreBar.hpp"
#include "mwChamferMill.hpp"
#include "mwCntrBore.hpp"
#include "mwCSink.hpp"
#include "mwCtrDrill.hpp"
#include "mwDoveMill.hpp"
#include "mwDrill.hpp"
#include "mwFaceMill.hpp"
#include "mwRadMill.hpp"
#include "mwReamer.hpp"
#include "mwTapLH.hpp"
#include "mwAngleUtils.hpp"
#include "mwTapRH.hpp"
#include "mwSpotDrill.hpp"
#include "mwSTLParserException.hpp"
#include "mwToolPath.hpp"
#include "mwToolpathLayered.hpp"
#include "mwMovesCompMethods.hpp"
#include "mwTPSection.hpp"
#include "mwTPContour.hpp"
#include "mwTPLink.hpp"
#include "mwTPPass.hpp"
#include "mwTPSlice.hpp"
#include "mwMovesAccessor.hpp"
#include "mwBarrelMill.hpp"
#include "mwBarrelAdvancedMill.hpp"
#include "mwBarrelBarrSecMill.hpp"
#include "mwBarrelDProfMill.hpp"
#include "mwBarrelLensMill.hpp"
#include "mwBarrelTangentMill.hpp"
#include "mwBarrelTangentMillConicalShaft.hpp"
#include "mwBarrelTaperMill.hpp"
#include "mwConvexTipMill.hpp"
#include "mw2dContourDomainSorter.hpp"
#include "mwCNCMoveHelpers.hpp"
#include "mwTPointUtils.hpp"
#include "mwcadcamException.hpp"
#include "mw2dPolygonizer.hpp"
#include "mwChainSawTool.hpp"
#include "mwTypedSawingTool.hpp"
#include "mwGenericSawingTool.hpp"
#include "mwSawingTool.hpp"
#include "mwTypedExtrudedTool.hpp"
#include "mwTriangleTurningTool.hpp"
#include "mwThreadTriangleTurningTool.hpp"
#include "mwDiamondTurningTool.hpp"
#include "mwParallelogramTurningTool.hpp"
#include "mwSquareTurningTool.hpp"
#include "mwPentagonalTurningTool.hpp"
#include "mwRoundTurningTool.hpp"
#include "mwOctagonalTurningTool.hpp"
#include "mwHexagonalTurningTool.hpp"
#include "mwGrooveTurningTool.hpp"
#include "mwGenericTool.hpp"
#include "mwChiselingTool.hpp"
#include "mwOpticDiamondTool.hpp"
#include "mwSpeedShapeTool.hpp"
#include "mwCrcMarker.hpp"
#include "mwContourTurningTool.hpp"
#include "mwThreadTriangleTurningTool.hpp"
#include "mwPrimeTurningTool.hpp"
#include "mwPotGrinderTool.hpp"
#include "mwThreadTapTool.hpp"
//#############################################################################
//mwCutterCompensation
#include "mwCutterCompensation.hpp"
//#############################################################################
//post
#include "mwPostException.hpp"
#include "mwRobMXPParams.hpp"
#include "mwMXPParam.hpp"
#include "mwRobMotionConstraintsParams.hpp"
#include "mwRobPositionControlSysParams.hpp"
#include "mwRobParametersCaster.hpp"
#include "mwRobMotionFiltersParams.hpp"
#include "mwRobVelocityCtrlDefParams.hpp"
#include "mwRobOptimizationsParams.hpp"
#include "mwRobTypes.hpp"
#include "mwRobCoordinateSystemTransformation.hpp"
#include "mwTransformation.hpp"
#include "mwPostedUtils.hpp"
#include "mwCNCMoveGrabber.hpp"
#include "mwExtendedPostedMove.hpp"
#include "mwPostedMove.hpp"
#include "mwMirrorAngle.hpp"
#include "mwPosted3axMove.hpp"
#include "mwPosted4axMove.hpp"
#include "mwPosted5axMove.hpp"
#include "mwPosted6axMove.hpp"
#include "mwPostedNaxMove.hpp"
#include "mwPostedTP.hpp"
#include "mwPostedMoveCloner.hpp"
#include "mwPostedMoveCaster.hpp"
#include "mwPostedVisitorMachMax.hpp"
#include "mwPostedVisitorMachMin.hpp"
#include "mwPostedVisitorPartMax.hpp"
#include "mwPostedVisitorPartMin.hpp"
#include "mwPostedVisitorMoveType.hpp"
#include "mwPostedVisitorBinOutput.hpp"
#include "mwPostedVisitorBinInput.hpp"
#include "mwMachDefBuilder.hpp"
#include "mwMachDefUtils.hpp"
#include "mwMachDef.hpp"
#include "mw3axMachDef.hpp"
#include "mw4axMachDef.hpp"
#include "mw5axMachDef.hpp"
#include "mw6axMachDef.hpp"
#include "mw5axControlDef.hpp"
#include "mwRopeVector.hpp"
#include "mwToolpathAlignment.hpp"
#include "mwPostedMoveVerifier.hpp"
#include "mwPostedTools.hpp"
#include "mwPosted3axTPInterpolate.hpp"
#include "mwPosted4axTPInterpolate.hpp"
#include "mwPosted5axTPInterpolate.hpp"
#include "mwPosted6axTPInterpolate.hpp"
#include "mwCTheta.hpp"
#include "mwPosted5axTPTimeCalc.hpp"
#include "mwMachDynamics.hpp"
#include "mwTransfMatrix.hpp"
#include "mwHeadAndTableRotation.hpp"
#include "mw4axHeadAndTableRotation.hpp"
#include "mw5axHeadAndTableRotation.hpp"
#include "mwPostLimitType.hpp"
#include "mwTurningPostUtils.hpp"
#include "mwPostedArcMove.hpp"
#include "mw6axCSMachDef.hpp"
#include "mwPostDefinition.hpp"
#include "mwGenericPostDef.hpp"
#include "mwPostDefinitionContainer.hpp"
#include "mwMachDefEqComparator.hpp"
//#############################################################################
//interactors
#include "mwLocale.hpp"
#include "mwLocaleDefault.hpp"

#if defined (_WIN32)
#include "mwIProgressHandler.hpp"
#include "mwIProgressHandlerBase.hpp"
#include "mwProgressKeeper.hpp"
#include "mwDisplayableProgressPoolSelector.hpp"
#endif
//#############################################################################
//measures
//tool approximation

#include "mwToolApproximationHelper.hpp"
//#############################################################################
//tool visualisation
#include "mwToolMeshCreator.hpp"
//#############################################################################
//verifiercore
#include "mwMeshOffseterLegacyInterface.hpp"

//#############################################################################
//MachSimMachDef
#include "mkdKinematicObject.hpp"
#include "mkdGeometry.hpp"
#include "mkdPolygonalGeometry.hpp"
#include "mkdDynamicGeometry.hpp"
#include "mkdToolpathGeometry.hpp"
#include "mkdCoordinateTransform.hpp"
#include "mkdRevolvingSet.hpp"
#include "mkdHeldTool.hpp"
#include "mkdAxis.hpp"
#include "mkdRotationalAxis.hpp"
#include "mkdTranslationalAxis.hpp"
#include "mkdWorkPiece.hpp"
#include "mkdFixture.hpp"
#include "mkdStockGeometry.hpp"
#include "mkdTailStock.hpp"
#include "mkdInitialStock.hpp"
#include "mkdWireEDMHead.hpp"
#include "mkdMountAdapter.hpp"
#include "mwMachSimCollisionGroup.hpp"
#include "mwMachsimMachDef.hpp"
#include "mwMachsimMachDefHelper.hpp"
#include "mwObjMapFiller.hpp"
#include "mwV2XMLReader.hpp"
#include "mwV2XMLWriter.hpp"
#include "mwMachSimMachDefSemanticException.hpp"
#include "mwMachSimMachDefException.hpp"
#include "mwIMachineStream.hpp"

//#############################################################################
	
#include "mwGenericExtrudedTool.hpp"

#endif
