# Generated by Django 4.1.3 on 2023-01-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('timestamp', models.BigIntegerField(db_column='Timestamp', primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='images/')),
                ('programname', models.CharField(blank=True, db_column='Programname', max_length=81, null=True)),
            ],
        ),
    ]
