# Generated by Django 4.1.3 on 2023-03-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_data", "0002_stlfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolsInChanger",
            fields=[
                (
                    "toolId",
                    models.BigIntegerField(
                        db_column="Tool ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "realOverallLength",
                    models.TextField(db_column="real Overall Length"),
                ),
                ("realDiameter", models.TextField(db_column="real Diameter")),
            ],
            options={
                "db_table": "toolsInChanger",
            },
        ),
    ]
