# Generated by Django 4.1.3 on 2023-01-25 11:50

from django.db import migrations, models
import live_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('live_data', '0002_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(upload_to=live_data.models.upload_path),
        ),
    ]
