# Generated by Django 4.1.3 on 2023-01-31 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('live_data', '0002_livemrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livemrs',
            name='stlFile',
            field=models.FileField(default=django.utils.timezone.now, upload_to='liveMrs/'),
            preserve_default=False,
        ),
    ]
