# Generated by Django 4.1.3 on 2022-11-25 15:42

from django.db import migrations, models
import simulation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("simulation", "0004_delete_simulation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "sim_ID",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("timestamp", models.BigIntegerField(db_column="Timestamp")),
                (
                    "cover",
                    models.FileField(
                        blank=True, null=True, upload_to=simulation.models.upload_path
                    ),
                ),
            ],
        ),
    ]
