# Generated by Django 4.1.3 on 2022-11-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0005_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="simulation",
            old_name="cover",
            new_name="nc_file",
        ),
        migrations.AddField(
            model_name="simulation",
            name="csv_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
