# Generated by Django 4.1.3 on 2022-11-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0006_rename_cover_simulation_nc_file_simulation_csv_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="sim_ID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
