# Generated by Django 4.1.3 on 2022-11-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0008_predicteddata"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="finished",
            field=models.BooleanField(default=False),
        ),
    ]
