# Generated by Django 4.1.3 on 2022-12-03 16:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0009_simulation_finished"),
    ]

    operations = [
        migrations.AddField(
            model_name="predicteddata",
            name="simulation",
            field=models.ForeignKey(
                db_column="Simulation",
                on_delete=django.db.models.deletion.CASCADE,
                to="simulation.simulation",
            ),
            preserve_default=False,
        ),
    ]
