# Generated by Django 4.1.3 on 2022-12-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0010_predicteddata_simulation"),
    ]

    operations = [
        migrations.AddField(
            model_name="predicteddata",
            name="stlPath",
            field=models.FilePathField(
                blank=True, null=True, path="Data\\CSV_Dateien", recursive=True
            ),
        ),
    ]
