# Generated by Django 4.1.3 on 2022-12-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0011_predicteddata_stlpath"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predicteddata",
            name="stlPath",
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
